# Generated by Django 4.0 on 2023-09-06 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0)),
                ('Accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='roomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='ROOMS/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.accommodation')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appauth.user'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
