# Generated by Django 4.0 on 2023-09-08 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
